// Generates docs/signals.md and docs/catalog.md from the source, so the reference never drifts.
//   node scripts/docs.ts          write both files
//   node scripts/docs.ts --check  exit 1 if either is stale (test/docs.test.ts runs the same check)
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { CATALOG, DEFAULT_SIGNATURES, SOFT_SIGNAL_REVISIONS } from '../src/index.ts';
import type { Group } from '../src/index.ts';

const root = new URL('../', import.meta.url);
const HEADER = '<!-- Generated by scripts/docs.ts from the source. Do not edit by hand: run `npm run docs`. -->\n\n';

const GROUPS: Record<Group, string> = {
  A: 'Hard automation and agent artefacts',
  E: 'Environment consistency',
  D: 'Input driving (CDP, synthetic events)',
  R: 'Rhythm (think time between actions)',
  C: 'Biometrics (typing, pointer dynamics)',
  H: 'Server header evidence (added by a server)',
  J: 'Judge (added by an optional server-side model)',
};

interface Row { code: string; group: Group; target: string; llr: Set<string>; hard: boolean; files: Set<string> }

const sources = (dir: URL): URL[] =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? sources(new URL(`${e.name}/`, dir)) : e.name.endsWith('.ts') ? [new URL(e.name, dir)] : []);

/** Every signal the engine can emit: literals in probes and features, plus the catalog's markers and globals. */
export function collectSignals(): Row[] {
  const rows = new Map<string, Row>();
  const add = (code: string, group: Group, target: string, llr: string, hard: boolean, file: string) => {
    const row = rows.get(code) ?? { code, group, target, llr: new Set(), hard: false, files: new Set() };
    row.llr.add(llr);
    row.hard ||= hard;
    row.files.add(file);
    rows.set(code, row);
  };
  const literal = /\{ ?code: '([a-z_]+\.[a-z0-9_.:]+)', group: '([A-Z])', target: '([a-z]+)', llr: (.+?)(?=, (?:hard|detail|family|agentId)\b| \}\)?;?|\s*\}\s*$)(, hard: true)?/gm;
  for (const url of sources(new URL('src/', root))) {
    const file = url.pathname.slice(url.pathname.lastIndexOf('/src/') + 1);
    for (const m of readFileSync(url, 'utf8').matchAll(literal)) add(m[1], m[2] as Group, m[3], m[4].trim(), !!m[5], file);
  }
  for (const m of DEFAULT_SIGNATURES.markers) add(m.code, 'A', m.target, String(m.llr ?? 9), (m.llr ?? 9) >= 8, 'src/catalog/fingerprinted.ts');
  for (const g of DEFAULT_SIGNATURES.globals) add(g.code, 'A', g.target, '9', true, 'src/catalog/fingerprinted.ts');
  // The engine rewrites these on emit (normalizeSoftSignal): document the effective weight.
  for (const [code, rev] of Object.entries(SOFT_SIGNAL_REVISIONS)) {
    const row = rows.get(code);
    if (row) Object.assign(row, { group: rev.group, llr: new Set([`≤ ${rev.llr}`]), hard: false });
  }
  return [...rows.values()].sort((a, b) => a.code.localeCompare(b.code));
}

const cell = (s: string) => s.replace(/\|/g, '\\|');

export function renderSignals(): string {
  const rows = collectSignals();
  const caps = DEFAULT_SIGNATURES.groupCaps;
  const shadow = new Set(DEFAULT_SIGNATURES.shadow ?? []);
  let out = `${HEADER}# Signal codes\n\n`;
  out += `Every signal the engine emits, from \`DEFAULT_SIGNATURES\` ${DEFAULT_SIGNATURES.version}. \`llr\` is the natural-log likelihood ratio: positive is evidence for automation, negative is evidence for a human. Some weights are expressions evaluated at run time (for example \`* soft\`, which shrinks environment evidence in privacy browsers). **Hard** signals short-circuit the verdict to ≥ 0.99 non-human. When the only hard evidence is an automation tool (a controller), it is a bot unless strong driving with think-then-act rhythm makes it an agent. See [How it works](how-it-works.md).\n\n`;
  if (shadow.size) out += `Codes marked **(shadow)** are listed in \`DEFAULT_SIGNATURES.shadow\`: reported, but weighted 0 (never hard) until promoted.\n\n`;
  out += `${rows.length} codes.\n`;
  for (const g of Object.keys(GROUPS) as Group[]) {
    const inGroup = rows.filter((r) => r.group === g);
    out += `\n## ${g}: ${GROUPS[g]}\n\nGroup cap ±${caps[g]}.\n\n`;
    if (!inGroup.length) { out += 'No client-side signals: these come from a server through `engine.addSignals()`.\n'; continue; }
    out += '| Code | Target | llr | Hard | Defined in |\n|---|---|---|---|---|\n';
    for (const r of inGroup) {
      const files = [...r.files].map((f) => `[${f.replace(/^src\//, '')}](../${f})`).join(', ');
      out += `| \`${r.code}\`${shadow.has(r.code) ? ' (shadow)' : ''} | ${r.target} | ${[...r.llr].map((l) => `\`${cell(l)}\``).join(', ')} | ${r.hard ? 'yes' : ''} | ${files} |\n`;
    }
  }
  return out;
}

export function renderCatalog(): string {
  const count = (k: 'class' | 'surface' | 'verifiable') =>
    Object.entries(CATALOG.reduce<Record<string, number>>((m, e) => ({ ...m, [e[k]]: (m[e[k]] ?? 0) + 1 }), {}))
      .sort((a, b) => b[1] - a[1]).map(([name, n]) => `\`${name}\` ${n}`).join(' · ');
  let out = `${HEADER}# Catalog\n\n`;
  out += `Every named bot and agent the engine and a server can identify: ${CATALOG.length} entries in [src/catalog/entries.ts](../src/catalog/entries.ts). Each cites the operator's own documentation. To add one, see [Extending](extending.md#add-an-agent-or-bot-to-the-catalog).\n\n`;
  out += `- **Class:** ${count('class')}\n- **Surface:** ${count('surface')}\n- **Strongest proof:** ${count('verifiable')}\n\n`;
  out += '`signed` = Web Bot Auth signatures · `ip` = published IP list · `rdns` = reverse DNS · `declared` = User-Agent only · `stealth` = no declaration, found by fingerprints or behaviour.\n\n';
  out += '| Name | Id | Class | Surface | Proof | Identified by |\n|---|---|---|---|---|---|\n';
  for (const e of [...CATALOG].sort((a, b) => a.id.localeCompare(b.id))) {
    const how = [
      e.identify.ua?.length && 'UA',
      e.identify.ipLists?.length && 'IP list',
      e.identify.rdns?.length && 'rDNS',
      e.identify.signatureAgent?.length && 'Web Bot Auth',
      e.identify.markers?.length && 'DOM markers',
      e.identify.globals?.length && 'globals',
    ].filter(Boolean).join(', ');
    out += `| [${cell(e.name)}](${e.source}) | \`${e.id}\` | ${e.class} | ${e.surface} | ${e.verifiable} | ${how} |\n`;
  }
  return out;
}

export const DOCS = { 'docs/signals.md': renderSignals, 'docs/catalog.md': renderCatalog };

if (import.meta.url === `file://${process.argv[1]}`) {
  const check = process.argv.includes('--check');
  let stale = false;
  for (const [path, render] of Object.entries(DOCS)) {
    const url = new URL(path, root);
    const next = render();
    let prev = '';
    try { prev = readFileSync(url, 'utf8'); } catch { /* new file */ }
    if (prev === next) continue;
    if (check) { console.error(`${path} is stale: run npm run docs`); stale = true; } else { writeFileSync(url, next); console.log(`wrote ${path}`); }
  }
  if (stale) process.exitCode = 1;
}
